---
development:
  cloud_name: hbp1mcgsv
  api_key: '329489874265454'
  api_secret: G1I_Apgdfqj3R5TeDXeWKlGjwEY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hbp1mcgsv
  api_key: '329489874265454'
  api_secret: G1I_Apgdfqj3R5TeDXeWKlGjwEY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hbp1mcgsv
  api_key: '329489874265454'
  api_secret: G1I_Apgdfqj3R5TeDXeWKlGjwEY
  enhance_image_tag: true
  static_image_support: false
